### PR TITLE
Adding Adafruit FONA library to MySensors to enable SMS/GSM capable nodes

### PR DESCRIPTION
**Pull request by GertSanders**
Adding the Adafruit FONA library allows using the SIM800L and SIM800H
modules available on the market.
This will allow nodes that have SMS or GSM capabilities.

### CODE REVIEW

**Comment by henrikekblad** [comment]
Hi, planning to add an example sketch showing how to use it as well?

**Comment by GertSanders** [comment]
Yes :-)

**Comment by fallberg** [comment]
Please verify that things compile before submitting. Jenkins is not supposed to be a testbed.
Also it appears that the branch is out of date so a merge from development will be needed before the PR has any chance of being mergable anyway.

**Comment by GertSanders** [comment]
hi Patrick,

the sketch compiles (both on Mac and PC, Arduino IDE version 1.6.7) and
runs fine on my node. I corrected 1 warning in my sketch. The rest of the
warnings are on the Adafruit library.

I can start cleaning up this library, but I have no idea if that will
resolve the Jenkins mails.

Most warnings are on deprecated conversions, which Arduino IDE does not
seem to mind.

Gert

**Comment by fallberg** [comment]
Are you sure you have enabled all compiler warnings in your IDE settings? You do not need to fix warnings in builtin libraries. Jenkins ignores (or should ignore) these. If you find a warning that had not been ignored please let me know and I will filter it. Jenkins gives a link in the comment here on github where you can examine what went wrong.

**Comment by GertSanders** [comment]
hi Patrick,

the only warning I now still have is because of following:

*extended initializer lists only available with -std=c++11*

This is because of following code in the Adafruit library:

Originally it was as follows:

char *tok = "";

This gives a warning. The only alternative gives the above warning.

char *tok = {};

This code above only fails (gives a warning) for Sensebender:


   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Onstabiel]#1888-MySensors:MysensorsMicro
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1888/>
   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Succes]#1889-arduino:nano
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1889/>
   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Succes]#1890-arduino:uno
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1890/>
   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Succes]#1891-arduino:pro
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1891/>
   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Succes]#1892-arduino:mega
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1892/>
   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Succes]#1893-esp8266com:generic
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1893/>
   - ArduinoIDEBuilder <http://ci.mysensors.org/job/ArduinoIDEBuilder/>[image:
   Succes]#1894-MySensors:mysensors_gw_native
   <http://ci.mysensors.org/job/ArduinoIDEBuilder/1894/>


I'm not sure what more I can do now.

Gert

**Comment by GertSanders** [comment]
Oh, and yes, I have ALL warnings active in the IDE :-)

**Comment by fallberg** [comment]
Generically speaking, if the warning is in a file that exists in git, it can and should be fixed. This also applies to libraries. Libraries not in git (that are provided by the arduino ide) does not need to (and cannot be) fixed.

**Comment by GertSanders** [comment]
So if a user can load the Adafruit FONA library through the library manager of the Arduino IDE I can basically leave it out of the MySensor GIT ?

Gert

**Comment by fallberg** [comment]
Yes. And the fewer extra libraries in the MySensors git, the better in my opinion. Just add to the maintenance to keep those up to date.

**Comment by GertSanders** [comment]
Ok, then I will close the pull request for the library and just add the sketch via a new pull request.

Gert

**Pull request closed without merging**
