### PR TITLE
Utilize digitalPinToInterrupt in examples

### PR DESCRIPTION
**Pull request by mfalkvidd**
The examples used hard-coded values or defines to convert digital
pin number to interrupt in calls to attachInterrupt and sleep.

This has confused several people, most recently in
https://forum.mysensors.org/topic/3880/gw-sleep-on-battery-powered-magnet-door-switch/

Let digitalPinToInterrupt handle this work instead.

I agree to CLA.

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build this please?

**Comment by fallberg** [comment]
Apparently, a recent upgrade on Jenkins have caused the PR verifier to fail. I apologize for the inconvenience and work on a solution.

**Comment by mfalkvidd** [comment]
No worries @fallberg

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, I just downgraded your pull requester plugin. Now, Jenkins, build this please, or I'll kick your ass for real!

**Comment by fallberg** [comment]
Jenkins, build this please. Pleeease...

**Comment by fallberg** [comment]
For some reason, the plugin no longer injects the environment variables it is supposed to. Not sure what to make of that as of now. Jenkins, build this please.

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
I blame the plugin for this so I created a issue and hope they resolve it: https://github.com/jenkinsci/ghprb-plugin/issues/342

**Comment by fallberg** [comment]
Shit's about to get real! Jenkins, build this please.

**Comment by henrikekblad** [comment]
Jenkins, build examples please.

**Comment by JohanElmis** [comment]
Dear, 

That  stuff I just found on  the web is admirable, you have to take a look <http://booklet.iparcelplus.com/e4mvxoy>

Sincerely yours, johan

**Pull request merged**
