### PR TITLE
MockMySensors Minor Fixes, all Sensors active

### PR DESCRIPTION
**Pull request by barduinor**
This version has all sensros active, the idea is to see if jenkings is able to compile.
Having just 1 sensor active wont compile 90% of the code

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by barduinor** [comment]
This is frustrating, it should not have picked up the remote-tracking branch (not my change).
If this causes any problem please close it

**Comment by fallberg** [comment]
Warnings found. Please fix: http://ci.mysensors.org/job/ArduinoBoardBuilder/287/warnings2Result/new/

**Comment by barduinor** [comment]
Commenting out these issues

**Pull request closed without merging**
