### PR TITLE
Small cleanups

### PR DESCRIPTION
**Pull request by tbowmo**
Corrected LED macro names in MyConfig.h, and updated library.json file with correct version number

(Pure cosmetic changes, won't break any builds..)

### CODE REVIEW

**Comment by fallberg** [comment]
Have you not signed cla? :)

**Comment by tbowmo** [comment]
I have signed it, a long time ago.. But something must have happened..

**Comment by tbowmo** [comment]
Happy now @fallberg ? :)

**Comment by fallberg** [comment]
I'm ecstatic!

**Pull request merged**
