### PR TITLE
Minor fixes, Only S_DOOR and V_ARMED active

### PR DESCRIPTION
**Pull request by barduinor**

### CODE REVIEW

**Comment by fallberg** [comment]
You do know that an open pull request gets updated when you push new commits to the branch the pull request stem from, right? No need to close and create new pull requests if you want to update an existing pull request. Just push more commits to tour branch. But please be clear in your commit messages so that it is easy to see in  the pull request what you update.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by barduinor** [comment]
Fallber,

I've seen it happen but just now i couldnt remember how to do it...
I guess its automatic, so in this case what should I have done? Create a comment and ask you to build it again?

**Comment by fallberg** [comment]
The pull request is from your branch HEAD, so just add a new commit to your branch that fixes the building issue (preferably to reduce Jenkins load and manual labor, test to build your commit locally before committing, the link Jenkins provides can help you determine under what circumstances your commit(s) fail to build so you can recreate the scenario on your own machine before submitting a fix).
Once you push your new commit on your branch to github, it will appear here, and you can optionally provide a comment here to state that you are finished and ready for Jenkins to give it another try.

**Comment by barduinor** [comment]
Thanks Fallberg, will do!
And again sorry for the trial end errors, I was trying to see how many active sensors I could have on my sketch fo jenkings to compile

**Comment by henrikekblad** [comment]
You could probably enable more if you put strings into flash memory.

Serial.println(F(“Hello World”));

Also, the build server should probably not be used for this type of trial'n'error. Just choose a low speced board on your local IDE (I.e. Uno) and find the limit on your computer.

**Comment by barduinor** [comment]
I did do that test on a uno and got as far as 12 sensors. I don't understand why Jenkins is complaining  with just 4. Also Jenkins report compiler warnings which I don't get on my arduinos ide. Let me know if you want to digg deeper into this within trial and error.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please (just to clean up the checks)

**Comment by fallberg** [comment]
Jenkins, build this please

**Pull request merged**
