### PR TITLE
Hardware definitions are moved to thier own repositories

### PR DESCRIPTION
**Pull request by tbowmo**
ArduinoHwSAMD and ArduinoHwAVR repositories added for the hardware definitions

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
That went even more well than it should. Jenkins, build this please (I want to set some things straight)

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please (now we should be good)

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by JohanElmis** [comment]
Hi friend! 
I've recently read some useful information, I guess it might be useful for you too, please  read at <http://ngygistunka.urbanmerchantexchange.com/e4gapz>

Warm regards, johan

**Comment by JohanElmis** [comment]
Hello, 

I just wanted to say how much  I miss you and share with you some  important information, just read it, you won't regret  <http://zuthylulte.mysticalentertainment.net/e4itntn>

Be well, johan

**Pull request merged**
