### PR TITLE
Signing docs proofread - fixing English and cleaning up wording

### PR DESCRIPTION
**Pull request by prawnpie**
I read through MySigning.h and noticed a lot of writing that could be cleaned up.

I hope this leaves the documentation better than I found it.

### CODE REVIEW

**Comment by virtual-maker** [comment]
@prawnpie 
> I hope this leaves the documentation better than I found it.

Basically yes, thanks for your effort.

But unfortunately you have introduced 3 trailing spaces at line ends like this below.
The red line is your current commit, the green line is the astyle recommendation:

image

Unfortunately these are valid issues for the astyle checker in the butler.sh check script.

You should remove the trailing spaces at lines 118, 509 and 875 and amend & push your last commit again.
Then it should work, at least with "Toll gate (Butler)".

**Comment by prawnpie** [comment]
@virtual-maker Sorry for the delay fixing this up. I've removed the trailing spaces.

**Comment by prawnpie** [comment]
@virtual-maker It seems the automation is still finding trailing spaces in my PR but I'm not finding any in the diff. Are there any tricks to locating where the tool is seeing trailing spaces? All I'm seeing is that there _are_ trailing spaces which isn't all that helpful.

**Comment by virtual-maker** [comment]
@prawnpie Hi,
> @virtual-maker Are there any tricks to locating where the tool is seeing trailing spaces?

In the Toll gate (Butler) there is this hint:
> MySensors have some [code contribution guidelines](https://www.mysensors.org/download/contributing) that I am afraid all contributers [sic] need to follow.

Best is to run this `.mystools/bootstrap-dev.sh` script after installing the required tools, mainly **Artistic Style - astyle**. This script adds two hooks to your .git settings which then run `astyle `and `cppcheck` before each commit you do. So you get informed if something is not OK with your commit. You will then also see all format fixed files (done by astyle) in your local repo.

Or use `astyle` with the right settings from command line on your own when you know how to do this.

**Comment by prawnpie** [comment]
@virtual-maker After installing `astyle` and `cppcheck` they didn't identify any issues. I think the issue was that my commit message stared with a lowercase character. Hopefully the checks go through this time.

I also discovered https://github.com/mysensors/MySensors/blob/development/.mystools/README.md which was very helpful for how to run `astyle` and `cppcheck`. Thanks for all of the tips.

**Comment by mfalkvidd** [comment]
Nice work! Thanks @prawnpie and @virtual-maker !

**Pull request merged**
