### PR TITLE
Fix MyIndication definitions

### PR DESCRIPTION
**Pull request by tekka007**
- Fix wrong definitions introduced in #462
- Fix compiler warnings
- Fix redefs related to SAMD

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by Yveaux** [comment]
Thanks guys for fixing this!

**Pull request merged**
