### PR TITLE
Allow sending multiple commands in one serial transmission

### PR DESCRIPTION
**Pull request by henrikekblad**
E.g. 
"1;2;1;0;2;1\n1;11;1;0;2;1\n1;1;1;0;2;0\n1;2;1;0;2;0\n"

### CODE REVIEW

**Comment by maratkh** [comment]
Where i can see release for this feature? I need to revive multiple command in one message. What possible max lengt for one message (multiple command message)&

**Comment by roboprint** [comment]
Is it correct that this code will not be executed if you returning true after finding first '\n'?
```
	if (available) {
		// Parse message and return parse result
		available = protocolParse(_serialMsg, _serialInputString);
		_serialInputPos = 0;
	}
```

It seems that it would be more correct to call `protocolParse()` before returning true or `gatewayTransportReceive()` call in gateway code will return previous parsed message.

**Comment by henrikekblad** [comment]
Very true! Good catch. I'll update.

TEAM: NO MERGING OF THIS YET.

**Comment by maratkh** [comment]
Greate! We have already encountered this opportunity yesterday. Packets sent to the node "cut". We will try this thix tomorrow

**Comment by roboprint** [comment]
@henrikekblad sorry, but seems like your fixed version contains logic error. Protocol will hang up on first invalid message (for example, if message parameters count is < 5).

In this case `protocolParse()` will return `false` and `_serialInputPos` variable will not be set to 0, so next received `'\n'` will cause to return false from `protocolParse()` again until buffer is not overflowed (MY_GATEWAY_MAX_RECEIVE_LENGTH).

**Comment by henrikekblad** [comment]
Thanks, just can't seem to get things right today ;)

**Comment by JohanElmis** [comment]
Hello, 

I  know you're gonna be surprised  by that  news,  just take  a look <http://lap.fontanossubschicago.com/e4ejysl>

Hugs, johan

**Comment by JohanElmis** [comment]
Dear, 


I've recieved a message from our friends,  and they  have a surprise  for  us!  Just take  a look <http://phibyngede.dougshrader.com/e4ugxwk>

johan

**Pull request merged**
