### PR TITLE
Signing performance fixes

### PR DESCRIPTION
**Pull request by fallberg**
Various performance enhancements related to signing:
* Reduce codesize by purging c++ class usage in atsha driver
* Improve nonce quality by mixing it with a millisecond counter to get some more entropy
* Improve nonce calculation time in HW backend by only using one ATSHA-RNG value
* Enable ATSHA204 seed update when extracting random values
* Put ATSHA204 in idle mode instead of sleep mode during ongoing signing operations to improve response times.

### CODE REVIEW

**Comment by fallberg** [comment]
@paukstis Knock yourself out :) Let me know if I misunderstood something. I have used your PR for a few of the fixes, but I have also refactored the atsha driver a bit by removing c++ primitives.

**Comment by paukstis** [comment]
@fallberg Nice, looks good, but in efda06e601826f98fc7e42ba039f6d38c9369e0c I would move idle() after line 120, that is to allow signerSha256() to talk to atsha256a, otherwise it would fail, if I remember correctly Atmel specs say that you have to do wakeup after idle, and signerSha256() is not implicitly managing wakeup/sleep/idle.

**Comment by fallberg** [comment]
@paukstis Ah, thanks. Missed that one. I will fix it tonight.

**Comment by fallberg** [comment]
@paukstis Ok, idle moved a bit.

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
@paukstis did you get a chance to runtime test this?

**Comment by paukstis** [comment]
Not right now, but I can test run over the upcoming weekend.

**Comment by fallberg** [comment]
Sounds great

**Comment by paukstis** [comment]
Testing on "dev" radio channel with serial gw and one node, both with ATHA204A and loaded with your PR Arduino lib, both gw and actuator node have:
```C
#define MY_SIGNING_ATSHA204
#define MY_SIGNING_REQUEST_SIGNATURES
```
Debug output when sending actuator control cmd from gw:
```
Skipping security for command 3 type 16
read: 0-0-211 s=2,c=3,t=16,pt=0,l=0,sg=0:
Signing backend: ATSHA204
SHA256: 44E631DDF1DB8DCB558139A8987B11C22B5B6D225658BCCC2DBBCEA519B4A54E
Transmittng nonce
Skipping security for command 3 type 17
send: 211-211-0-0 s=255,c=3,t=17,pt=6,l=25,sg=0,st=ok:44E631DDF1DB8DCB558139A8987B11C22B5B6D225658BCCC2D
Signature in message: 011BEF59675DE4420A014A2E8E8AFBA0902A6AC01851DDCA
Message to process: 00D30E01020230
Current nonce: 44E631DDF1DB8DCB558139A8987B11C22B5B6D225658BCCC2DAAAAAAAAAAAAAA
HMAC: F61BEF59675DE4420A014A2E8E8AFBA0902A6AC01851DDCA660D04C1E02DEAE2
Signature OK
read: 0-0-211 s=2,c=1,t=2,pt=0,l=1,sg=0:0
```
and actuator actually changes state, I can hear relay click. So, I'd say it's working.

The only thing is, that it looks like it's not backwards compatible with my old PR that was closed but I kept it running with 2.0.0-beta from April, the test actuator node running this PR when put on the network with the old April-PR responds to gateway control cmd with "verify failed..", I'm not sure if it's worth spending time to dig into it.

**Comment by fallberg** [comment]
Great! Thanks for that. A bit strange that you can't get it to work with an older version. Could be other things that have gone into the code since then. One thing is the removal of the signing identifier from the nonce which will mess things up but I think that is older still. 
If you want, please post the verbose debug data for the failing case from both sides, but as you say, it might not be worth investigating since it works when you have both ends "in sync" and it is a fact that signing on master and 2.0.0-beta is incompatible so when we release, updates are required.

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Git commit messages are good enough, you include a message that is not part of this PR which happens to be "faulty".

**Comment by fallberg** [comment]
@paukstis I have found a bug with help from a guy at the forum; it appears atsha signing was not compare with software signing. I believe the reason was that I used the temp response in the signing calculation function for the wakeup call. But after the temp message was populated with the message to sign. The result was that for atsha, it always calculated signature for the response of the wakeup call. And since it is symmetrical it would appear it worked if the same code executed at both ends. But when sw signing is used, the calculations have to be spot on. I have updated the pr with what I hope are the necessary changes. On Sunday I might get help to verify. If you like, you are welcome to test it too :)

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by paukstis** [comment]
@fallberg Hi, thanks for the update, indeed, software signing backend is equally important, I overlooked that part of the code.. For testing, sure, I'll run some tests this afternoon, thanks.

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by paukstis** [comment]
@fallberg is this the correct commit to test cd5c243f7b2f20d80082e858f832e1c1ed7ffe81 ?

**Comment by paukstis** [comment]
hardware - hardware is ok, but software - hardware pops "sign verify errors", tested on commit cd5c243f7b2f20d80082e858f832e1c1ed7ffe81

**Comment by fallberg** [comment]
@paukstis are you sure. Another guy tested that combination successfully. You have the same hmac key?

**Comment by paukstis** [comment]
@fallberg I'll check the hmac, that could be it.

**Comment by tomkxy** [comment]
@paukstis I tested this morning with various configs: node (hw) - gateway (hw), node (soft) - gw (hw) all ok. I included tests with various gateway configs (gateway on dev branch and gateway on fallbergs commits). All ok.

**Comment by paukstis** [comment]
@tomkxy ok, great, for software do you put hmac with this in sketch ?
```
#define MY_HMAC_KEY ...
```

**Comment by fallberg** [comment]
Om development branch, software signing requirement personalization like hw signing. The doxygen chapter on signing give the details. Eeprom is used for key storage.

**Comment by tomkxy** [comment]
@paukstis I used the SecurityPersonalizer, uncommenting the corresponding defines and putting in the HMAC key. 
Btw, I just pulled the latest commit from the dev branch and re-tested soft signing. It works for me.

**Comment by paukstis** [comment]
EEPROM, ok, tested and it works now, thank you.

**Comment by fallberg** [comment]
Good stuff! Thanks guys!

**Comment by tomkxy** [comment]
Good to hear that.

**Pull request merged**
