### PR TITLE
I_DISCOVER_RESPONSE embryo

### PR DESCRIPTION
**Pull request by tekka007**
***WIP*** Implementation of I_DISCOVER / _RESPONSE:
- Fast discovery, parent node id
- general information about node
- architecture information (IDs, freq, voltage, etc.)
- bootloader information (vers, etc.) 
- transport (config, freq, encryption, signing, etc.)

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Please skip the "/**" and use "/*" for the copyright header blocks. It is a doxygen tag and it messes with the generated output.

**Comment by fallberg** [comment]
Damn escaping... Trying again... 
Use /\* instead of /\*\*

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by tekka007** [comment]
Postponed, >2.0.0

**Pull request closed without merging**
