### PR TITLE
Rain Gauge

### PR DESCRIPTION
**Pull request by petewill**
Uploading initial rain gauge code and Vera files

### CODE REVIEW

**Comment by henrikekblad** [comment]
Thanks Pete, the vera device files should probably go into Vera-repository. Don't you think?

**Comment by petewill** [comment]
Sure, that sounds good.  I just wanted people to be able to find them but it's probably better to put them there.  Do you want me to submit a new pull request? I'm not really sure how all this normally works.

**Comment by henrikekblad** [comment]
Just do another commit/push with the files removed (github will automatically merge these changes to your previous pull request).

Then do another PR to the Vera repository (with the device files).

If I mess around here you wont get the "credit" for the files :)

**Comment by petewill** [comment]
You were right, github is smart!  I removed the files and I didn't have to make any changes to this pull request.

I don't need the credit this is Jim's creation.  Just trying to help when I can. :)

**Pull request merged**
