### PR TITLE
update RFM69 driver

### LINKED ISSUE #407: RFM69.cpp setFrequency
This allows for direct entry of real operating frequency...

Now:
~~~
void RFM69::setFrequency (uint32_t FRF)
{
  writeReg(REG_FRFMSB, FRF >> 16);
  writeReg(REG_FRFMID, FRF >> 8);
  writeReg(REG_FRFLSB, FRF);
}
~~

should be:

~~~

// The crystal oscillator frequency of the RF69 module
#define MYRF69_FXOSC 32000000.0
// The Frequency Synthesizer step = MYRF69_FXOSC / 2^^19
#define MYRF69_FSTEP  (MYRF69_FXOSC / 524288)

void RF69::setFrequency (float centre)
{
    // Frf = FRF / FSTEP
    uint32_t frf = (uint32_t)((centre * 1000000.0) / MYRF69_FSTEP);
     writeReg(REG_FRFMSB, (frf >> 16) & 0xff);
     writeReg(REG_FRFMID, (frf >> 8) & 0xff);
     writeReg(REG_FRFLSB, frf & 0xff);
}

~~~

### LINKED ISSUE #410: st=fail
From time to time, I get st=fail, if I put a wait(200) after each send() they are gone...
using 2.0.0 beta
Radio: RFM69HW

There must be some timing issue in the stack, one should NOT need to add the wait() to the code to fix something like this...

I always get an st=fail on startup, might be related:

send: 6-6-0-0 s=255,c=3,t=15,pt=0,l=2,sg=0,st=ok:
send: 6-6-0-0 s=255,c=0,t=18,pt=0,l=10,sg=0,st=fail:2.0.0-beta  <-------------------
send: 6-6-0-0 s=255,c=3,t=6,pt=1,l=1,sg=0,st=ok:0
send: 6-6-0-0 s=255,c=3,t=11,pt=0,l=24,sg=0,st=ok:Water and Pressure Meter
send: 6-6-0-0 s=255,c=3,t=12,pt=0,l=4,sg=0,st=fail:1.2b  <-------------------
send: 6-6-0-0 s=1,c=0,t=21,pt=0,l=0,sg=0,st=ok:
Init complete, id=6, parent=0, distance=1

### LINKED ISSUE #436: Using Current RFM69 driver
I have started using the newer RFM69 driver from LowPowerLab in 2.0b, this fix my occasional ST-fail issue with this radio and allows me to remove all of my wait(200) after each send. I'm also informed, that it may fixes the problem with the Ethernet gateway sharing of the hardware SPI, but I have not tested yet...

These are the ONLY changes that I made to there files:
In RFM69.cpp
~~~
from:
#include <RFM69.h>
#include <RFM69registers.h>
#include <SPI.h>

To:
#include "RFM69.h"
#include "RFM69registers.h"
#include <SPI.h>
~~~

https://github.com/LowPowerLab/RFM69

### PR DESCRIPTION
**Pull request by tekka007**
- fixes #436
- fixes #410
- fixes #407

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by Yveaux** [comment]
Seems spi transactions are missing, and Spi protection from interrupt access.

**Comment by tekka007** [comment]
@Yveaux see RFM69::select()

**Comment by Yveaux** [comment]
@tekka007 Bit late, but that's not what I mean with SPI transactions.
See e.g. https://www.arduino.cc/en/Reference/SPISettings, https://www.arduino.cc/en/Reference/SPIbeginTransaction and https://www.arduino.cc/en/Reference/SPIusingInterrupt.
These is the Arduino API to use SPI transfers in a concurrent, interrupt-safe way.

**Comment by tekka007** [comment]
@Yveaux yes, SPI transactions have been added to the original library but the changes were reverted later without comment (see https://github.com/LowPowerLab/RFM69/commit/ec90680e008c366dc7340ec1aada3942f8592707). In addition, ESP does not support atomic sections / SPI.usinginterrupt yet (https://github.com/esp8266/Arduino/issues/1943). If you have the HW and bandwidth to test (at least for AVR), please feel free to submit a PR.

**Pull request merged**
