### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Yveaux**
Fix crash at startup

### CODE REVIEW

**Comment by henrikekblad** [comment]
Jenkins, build this please.

**Comment by fallberg** [comment]
Not yet sure why Jenkins has become senil, but at least he only builds once again.

**Comment by henrikekblad** [comment]
Hmm.. did it fail on the second build?

**Comment by fallberg** [comment]
Jenkins still seem to be very happy to build stuff. The error was due to a busy x server and can be discarded. Not related to any coding issue.

**Pull request merged**
