### PR TITLE
Mixed signing 2

### PR DESCRIPTION
**Pull request by fleinze**
to match the description in http://forum.mysensors.org/topic/1021/security-introducing-signing-support-to-mysensors :
> However, the difference is that the gateway will only require signed messages from nodes it knows in turn require signed messages.

### CODE REVIEW

**Comment by fallberg** [comment]
@fleinze Have you tested this change with a GW that require signatures, and two nodes (on that is "secure" and one that is "insecure")?
Expected behavior:
GW<->"secure node": all messages are signed in both directions
GW<->"insecure node": no messages are signed at all

I cannot currently verify the change myself I am afraid. But this is at least how it is supposed to work.

Also, you should be able to set the GW to not require signatures, then the behavior should be like this:
GW<->"secure node": all messages to the node is signed, no messages to the GW is signed
GW<->"insecure node": no messages are signed at all
It would be great if you could test this usecase as well.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fleinze** [comment]
thank you fallberg, I did test the usecases:
"insecure" GW -> "secure" node: messages to gateway are not signed, messages to node are signed
"insecure" GW -> "insecure" node: no signing at all

**Comment by fallberg** [comment]
Ok, so all testcases did pass as expected?

**Comment by fleinze** [comment]
I just did final tests with a clean copy: (true means requires signing, false means doesn't require signing, as in the MySigning constructor)
GW(true) -> node(true): all messages signed
GW(true) -> node(false): no messages signed
GW(false) -> node(false): no messages signed
GW(false) -> node(true): messages to the gw are not signed, messages to the node are signed
So, all testcases as expected.

**Comment by fallberg** [comment]
Thanks @fleinze for finding and fixing this!

**Pull request merged**
