### PR TITLE
Renamed MySensor.h -> MySensors.h

### LINKED ISSUE #480: Naming conventions
While not explicitly stated, if you look at the example given [here](http://playground.arduino.cc/Code/Library)

```
MyLibrary.cpp (if downloaded) in /hardware/libraries/MyLibrary/MyLibrary.cpp change MyLibrary to whatever the name of the library you want to investigate
```

and if you look at every other library out there, the naming scheme is `LIBRARYNAME/LIBRARYNAME.h` whereas in this project it is MySensors/MySensor.h  (missing plural s at end of MySensor before the '.h').  When using the arduino-mk makefile, you get stuff like this:

```
Qhydro.ino:46:22: fatal error: MySensor.h: No such file or directory
 #include <MySensor.h>
```

now you can go into your libraries folder and `ln -s MySensors MySensor` and get around this, but this seems hackish, and I'm left wondering if there is a good reason to be breaking convention here?

### PR DESCRIPTION
**Pull request by tbowmo**
And replaced all references to MySensor.h in examples with MySensors.h

fixes #480

### CODE REVIEW

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Pull request merged**
