### PR TITLE
Hardened (dis)connections

### PR DESCRIPTION
**Pull request by Yveaux**
Occasionally watchdog would trip causing a reset when a client (dis)connected.
Added support fot multiple sessions (Currently 5 max. Each connection
costs RAM!)
Each session can send data to the gateway. Data from the gateway will be
broadcasted to all connected clients.
Added serial logging of client (dis)connections. Inspect serial terminal
in case of problems.

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins is in a bad mood. It is not certain he will listen at the moment. Jenkins, build this please.

**Comment by Yveaux** [comment]
Time to teach hime a lesson then!
He also only listens to core dev team...

**Comment by fallberg** [comment]
Jenkins does not even listen to them right now. Jenkins, build this please.

**Comment by fallberg** [comment]
ok to test

**Comment by tbowmo** [comment]
He probably need to be send of to a boarding school, and learn to behave :)
Den 04/09/2015 20.07 skrev "Patrick Fallberg" <notifications@github.com>:

**Comment by fallberg** [comment]
Jenkins, build this please. Or I'll kick your ass!

**Comment by Yveaux** [comment]
That did it! ;-)

**Comment by henrikekblad** [comment]
Multi connections, nice!

**Pull request merged**
