### PR TITLE
Added return value for atsha204_getSerialNumber

### PR DESCRIPTION
**Pull request by tbowmo**
Also cleaned up trailing whitespaces in atsha204 core driver

### CODE REVIEW

**Comment by tbowmo** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
If tested ok on target with atsha, this has my blessing

**Comment by fallberg** [comment]
Jenkins, build this please (testing ide 1.6.9)

**Comment by fallberg** [comment]
Jenkins, build this please (fixed typo)

**Comment by fallberg** [comment]
Jenkins, build this please. Some more work needed before 1.6.9 can be used on jenkins... Were back on 1.6.6

**Comment by fallberg** [comment]
Jenkins, build this please (another go at 1.6.9)

**Comment by fallberg** [comment]
Jenkins, build this please (another go at 1.6.9)

**Comment by fallberg** [comment]
Jenkins, build this please (esp port seem broken for 1.6.9 still, reverting back to 1.6.6 yet again)

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Comment by tbowmo** [comment]
Closing this PR, as it's not strictly needed, and was more of a nice to have.

**Comment by tekka007** [comment]
Implementation planned for 2.1.0

**Comment by JohanElmis** [comment]
Greetings, 

I've found  a very easy  tutorial on the stuff we  were talking  about,  look here <http://support.wasiq.com/e4nurrbx>

Be well, johan

**Comment by JohanElmis** [comment]
Dear! 

We've got  some  surprising  news, you're gonna  love it!  Just read it  here  <http://enter.ninesixx.com/e4wbqhy>

See you soon, johan

**Comment by JohanElmis** [comment]
Greetings, 


If you were  looking for something  really exciting I think you'd love that, just take  a look <http://cheap.paulheintzelman.com/e4hemvei>

Wishes, johan

**Comment by JohanElmis** [comment]
Hello! 


Look  what I've got! That's just great, just take a look at those cool  things  <http://quejetonu.cateringbyemilia.com/e4sluaz>

My best to you, johan

**Pull request merged**
