### PR TITLE
Update MockMySensors.ino

### PR DESCRIPTION
**Pull request by barduinor**
Minor Fixes
Conversion to lib 1.5

Jenkins, build this please

### CODE REVIEW

**Comment by barduinor** [comment]
Jenkins, build this please

**Comment by tbowmo** [comment]
Only members of the mysensors organisation on github can command Jenkins,
build this please
Den 13/08/2015 05.11 skrev "Barduino" <notifications@github.com>:

**Comment by fallberg** [comment]
Development branch is not yet in sync with master and therefore Jenkins cannot fully verify this PR.

**Comment by fallberg** [comment]
Jenkins, build this please (this is just a test, output/result is meaningless)

**Comment by fallberg** [comment]
Jenkins, build this please again

**Comment by barduinor** [comment]
fallberg
Can you help me understand what am i doing wrong here?
The test results do not have any information that I can see...

**Comment by fallberg** [comment]
I am currently changing some jenkins behaviour. I will have to ask you to do a merge or rebase from master and update the pull request later and then jenkins should be able to build your pull request as it is supposed to. Stay tuned :)

**Comment by barduinor** [comment]
Cool, thanks!

**Comment by fallberg** [comment]
I now see that you are targeting development and not master with your PR(s). So please disregard my previous comment as you will not be immediately affected since master and development diverges. Until development branch get updated with the fixes on master, building PRs targeting development will never work. @henrikekblad please consider merging from master to development soon so we get this ability.

**Comment by barduinor** [comment]
no worries, ill do it later

**Comment by fallberg** [comment]
Sorry for the confusion :) We are just getting started with Jenkins. There are still a few small things to sort but hopefully we will soon be completely on track and although it could be some annoyance to developers sending PRs that their build does not go through because of a simple warning, the goal is to strengthen the codebase we all share and also to make sure it works for a number of different boards (we currently build all examples for five different Arduino and MySensors specific boards, and that number will go up) so by doing this we can better ensure stability.

**Pull request closed without merging**
