### PR TITLE
Update DallasTemperatureSensor.ino

### PR DESCRIPTION
**Pull request by Kolbi**
Really really small optimisation

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by Kolbi** [comment]
Is it possible that the pull requests didn't merged properly?

**Comment by fallberg** [comment]
You closed the pull request.

**Comment by Kolbi** [comment]
Sorry my mistake deleted the branchs before checking PR. Would you be so kind and tell Jenkins to build it again? :)

**Comment by fallberg** [comment]
Jenkins, build this please

**Pull request merged**
