### PR TITLE
Update MockMySensors.ino

### PR DESCRIPTION
**Pull request by barduinor**
Minor fixes.
Finally had a chance to test this.
Works fine with all mocking sensors in a mega

### CODE REVIEW

**Comment by barduinor** [comment]
Jenkins,

Maybe this shouldnt go forward...

I've just realised folks fixed my code (added signing and some pin declaration) and I didnt update my local copy first.

Sorry about this...

**Comment by fallberg** [comment]
So this pr can be closed?

**Comment by fallberg** [comment]
Closing this PR since #163 exists. I believe that PR replaces this one.

**Comment by barduinor** [comment]
That is correct

**Pull request closed without merging**
