### PR TITLE
MyMessage.h / MockMySensors changes

### PR DESCRIPTION
**Pull request by gizmocuz**
MyMessage.h: Added some comments and presentation types from the web site, fixed a small typo

MockMySensors sketch: Fixed some small issues to conform to the 1.5 API (S_HEATER still needs to be done)

### CODE REVIEW

**Comment by henrikekblad** [comment]
Jenkins, build this please.

**Comment by henrikekblad** [comment]
Thanks @gizmocuz, 
I see that you included some changes in MockMySensors.ino, so we better check with @barduinor as he have had a couple of PRs to fix things himself... 

@barduinor, Are you ok with changes here?

**Comment by gizmocuz** [comment]
Sure, there small changes in the mockup sketch

**Comment by barduinor** [comment]
Sure, I'll pull from it again

**Comment by gizmocuz** [comment]
the S_HEATER / S_HVAC needs some work...

at the moment i am very confused about what value types are supported for the presentation types.

the comments for the S_xxx types do not match the comments from the V_xxx types and visa versa

Would be great if this got cleaned up once and for all ;)

**Comment by gizmocuz** [comment]
... and of course the corresponding example sketches needs to use all those V_xxxx values as well.
(Ok if it is only logging them)

**Comment by barduinor** [comment]
This was originally done for lib 1.4, ported to 1.5, but still work in progress (even the port) and there were changes in the HVAC sensor/messages and a few more.
There is no formal relation between sensors (S_XXXX) and Message values types (V_XXXX).
The only source we have are documantation of the lib 1.5 and comments in Message.h
Ultimately you can decide to send any combination of mesages for a sensor.
The idea for the MockMySensors is to implement the Sensor/Message somvination as it is described in the API 1.5 but still work in progress.
I tried to update the dev branch a few days ago without success...

**Comment by gizmocuz** [comment]
Sorry i was referring to the documentation of the 1.5 lib and comments in Message.h
The mockup code is perfect to get most tested

**Pull request merged**
