### PR TITLE
Present the gateway itself before gateway child sensors

### PR DESCRIPTION
**Pull request by davidedmundson**
This fixes child nodes working under home-assistant

### CODE REVIEW

**Comment by henrikekblad** [comment]
Could this be fixed in HomeAssistant instead? A bit worried how other controllers would react if we introduced this message.

**Comment by davidedmundson** [comment]
Other controllers will need it too.

Gateways having child sensors is new. 
Its mysensors "breaking" behavior by now having sensors without a presented sensor.

This patch brings the serial API to be the same as previous releases from the POV of the controller.

**Comment by henrikekblad** [comment]
Hmm, true. It should probably be defined as a repeater anyhow. Could you update this?

**Comment by henrikekblad** [comment]
When thinking a bit more it should probably be:

#if defined(MY_REPEATER_FEATURE)
   present(NODE_SENSOR_ID, S_ARDUINO_REPEATER);
#else
   present(NODE_SENSOR_ID, S_ARDUINO_NODE);
#endif

**Comment by henrikekblad** [comment]
Fixed in #426

**Pull request closed without merging**
