### PR TITLE
Add wait() helper that doesn't sleep. 

### PR DESCRIPTION
**Pull request by rhooper**
Adds a wait helper, useful for repeaters and sensors that read from the network.

### CODE REVIEW

**Comment by henrikekblad** [comment]
Thanks. This could be useful in non-sleeping nodes. 

Would you mind adding your name to the CLA so I can merge it?
https://www.clahub.com/agreements/mysensors/Arduino

**Comment by rhooper** [comment]
I'd love to sign the CLA, but I keep getting an error "We're sorry, but something went wrong." every time I try.

**Comment by henrikekblad** [comment]
WTF.. another community member complained about this a recently. All the sudden he could sign it. Their service seems a bit shaky.  
Let me check with the CLAHub folks.

**Comment by henrikekblad** [comment]
Ok, added an issue over at CLAHub.. In the meantime you could perhaps reply to this and say "I Agree to CLA". 

Sorry for the inconvenience. This is all pretty annoying.

**Comment by rhooper** [comment]
I agree to the CLA and am contributing as an individual.  I do work as a software developer, but my contract excludes works not related to my company's lines of business.  As they deal with domain names, there is no conflict.

**Pull request merged**
