### PR TITLE
Heatpump / air conditioner library 'HeatpumpIR' merged into MySensors

### PR DESCRIPTION
**Pull request by ToniA**
* Added libraries 'HeatpumpIR' and 'Timer' (the HeatpumpIR examples require Timer)
* An example on how to use HeatpumpIR on libraries/MySensors/examples/HeatpumpIRController

### CODE REVIEW

**Comment by henrikekblad** [comment]
jenkins, add author to whitelist please

**Comment by henrikekblad** [comment]
Jenkins, add author to whitelist please

Jenkins, build this please

**Comment by henrikekblad** [comment]
You seem to get warnings on the F-macros used in example-sketch. As they are being ignored by the compiler. Please remove them or test locally if Serial.println(PSTR("STRING")) works better.

You'll see the warnings by enabling it under settings in the Arduino IDE.

Cheers
Henrik

**Comment by fallberg** [comment]
The library also incorrectly uses the PROGMEM attribute:
http://ci.mysensors.org/job/ArduinoBoardBuilder/a_tool=%2Fopt%2Farduino-1.6.5%2Farduino-headless,arch=avr,board=MysensorsMicro,example=HeatpumpIRController%2FHeatpumpIRController.ino,freq=1000000,mcu=atmega328p,pkg=MySensors/864/consoleFull#-303137203dfb59020-c3f1-4bab-98de-5c515749ecbd

This is discussed in various forums online. Perhaps a hint on what could cause this is available there.
Ex. http://forum.arduino.cc/index.php?topic=120212.0
and
http://www.avrfreaks.net/forum/warning-progmem-attribute-ignored

Cheers
Patrick

**Comment by henrikekblad** [comment]
Thanks @ToniA

**Pull request merged**
