### PR TITLE
Update MyMainESP8266 to compile with ESPlib 2.3.0

### PR DESCRIPTION
**Pull request by tekka007**
- updates to MyMainESP8266.cpp
- hwReboot: use ESP.restart() instead of wdt timeout

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please (some warnings filtered)

**Comment by fallberg** [comment]
Jenkins, build this please (hopefully, correct warnings filtered)

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Hm, I am not sure that error is bsp related. @tekka007 any ideas?

**Comment by tekka007** [comment]
Yeah, the missing file schedule.h is only included in the 2.3.0 port

**Comment by fallberg** [comment]
Ok, so safe to merge?

**Comment by tekka007** [comment]
Yes, for 2.3.0

**Comment by fallberg** [comment]
So it will break earlier bsp:s?

**Comment by tekka007** [comment]
I assume so, but there is no point of sticking to older releases...

**Comment by JohanElmis** [comment]
Hi,

You  have  to see that amazing stuff! I  couldn't believe my eyes, that's  really not a joke. Just  take a  look  <http://like.ticketsforvets.com/e4kskhiq>

Very truly yours, johan@elmerfjord.com

**Pull request merged**
