### PR TITLE
Signing troubleshooting guide in Doxygen

### PR DESCRIPTION
**Pull request by fallberg**
Also added debug prints for RF failures.

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build this please (rerender doxygen)

**Comment by JohanElmis** [comment]
Hi,

I've  found very nice driving glasses that perfectly protect from brigth sunlight, and they are  also so stylish, just take a look <http://keep.workbook-1.com/e4zph>


Best wishes, johan@elmerfjord.com

**Comment by JohanElmis** [comment]
Hey friend, 

We've been to the theater recently, the performance was just fabulous! I'm  so  excited! Just take a look at it <http://dahiphege.dynamohomes.com/e4wpca>

See you around, johan

**Comment by JohanElmis** [comment]
Hi! 

Have you  seen that latest movie? I  don't know what all the  fuss is about. Before you watch it read  a review here <http://jafecypro.gvmlawoffice.com/e4sbucy>

johan

**Pull request merged**
