### PR TITLE
Merge w/ Gizmocuz; Implement S_COVER, S_IR, S_SCENE

### PR DESCRIPTION
**Pull request by barduinor**

### CODE REVIEW

**Comment by bblacey** [comment]
Jenkins, add author to whitelist please

**Comment by barduinor** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
@barduinor , you don't need to ask Jenkins to build. Since you are whitelisted, Jenkins does it automatically. Unless you have somehow pushed new changes to the PR that Jenkins have not picked up, but he should.

**Comment by barduinor** [comment]
@fallberg, that was exactly what happened when i noticed that I hadn't updated the read.me.

**Comment by fallberg** [comment]
not sure I understand what you mean. I don't see a new commit in the PR since 2 days ago.

**Comment by barduinor** [comment]
Ok let me explain then.
I commited my changes to mockmysensors.ino and created the pull request.
bblacey added me to the white list and jenkins immediattly started the build.
(Merge w/ Gizmocuz; Implement S_COVER, S_IR, S_SCENE / a198653/ http://ci.mysensors.org/job/MySensorsArduinoPR/82/)

I noticed that I hadn't updated the read.me, i updated it and did a new commit.
(Change Log / 92b1b8d)

When jenkins finished the 1st build it stopped, the build for the new commit was still pending.
So I issues a build this j... command and it build again
http://ci.mysensors.org/job/MySensorsArduinoPR/83/

**Comment by fallberg** [comment]
Hm. Strange. Because according to the timeline, your (Change Log / 92b1b8d) as added before anyone made any comment. Usually new commits enter in the comment "timeline". Never mind :)

**Comment by fallberg** [comment]
Triggering a jenkins build to stress test the build server. If output is a failure, it can be disregarded (there is nothing "Jenkins wrong" with this PR).
Jenkins, build this please.

**Comment by fallberg** [comment]
Just another stress test: Jenkins, build this please

**Comment by barduinor** [comment]
@fallberg, im curious, once the checks are passed what to I need to do?

**Comment by fallberg** [comment]
Nothing. Just wait for Grandmaster @henrikekblad to approve :) (or another core team member in case he needs review help)

**Pull request merged**
