### PR TITLE
Update MyConfig.h

### PR DESCRIPTION
**Pull request by Kolbi**
added some hints to MY_RF_24_CHANNEL selection

### CODE REVIEW

**Comment by henrikekblad** [comment]
Jenkins, add author to whitelist please

**Comment by fallberg** [comment]
I notice a lot of pull requests and all commit messages just indicate the file that was updated. It would be better if the commit message stated what was changed. Then one could just read the git log in condensed form to get an overview on what has happened. This is a great guide to writing good commit messages: http://chris.beams.io/posts/git-commit

Existing pr:s can be updated by amending the commit and rewrite the message (git commit --amend) and then force pushing the branch to github (git checkout <branch>;git push origin HEAD:<branch> -f)

**Comment by Kolbi** [comment]
I'm relativly new to github and I'm mostly only using the web version of github :+1: but I'm going to try to create less PRs and with a better description.

**Comment by fallberg** [comment]
That's perfectly ok. Just make sure you understand that git commits is a different thing from GitHub pr comments/descriptions :)
I know that github has a bad habit of putting a default headline that says "Update (file)", but generally, just delete that and give a brief description of what that particular commit actually does and give a more elaborate explanation in the "body". The link I sent explains in a good way how and why this is a good idea :)

**Pull request closed without merging**
