### PR TITLE
Create RGB-3D.ino

### PR DESCRIPTION
**Pull request by vil1driver**
RGB led strip controled with three dimmers + one On/Off for run/stop rgb color cycle :p

### CODE REVIEW

**Comment by henrikekblad** [comment]
Jenins, build this please.

**Comment by fallberg** [comment]
You need to spell Jenkins correctly @henrikekblad ;)

**Comment by henrikekblad** [comment]
Jenkins, build this please ;)

**Comment by henrikekblad** [comment]
Really nice! 

In version 1.5 of the mysensors library you can also use the V_RGB to receive/send all color components to the controller in one message. Payload should be an ASCII RGB hex string. E.g. "FF0000" for red.

But as not all controllers support this yet it might be good to add an #define option to use this feature when presenting device (S_RGB)? For incoming messages you could support both V_DIMMER and V_RGB ways perhaps?

I.e. 
#define USE_1_5_RGB_MESSAGE

Code for extracting color components from message:
```(payload = "FF3Fa0";)
int number = (int) strtol( &payload, NULL, 16);
int r = number >> 16;
int g = number >> 8 & 0xFF;
int b = number & 0xFF;
```

**Comment by vil1driver** [comment]
Hi,

Thanks, i know it but i made this scketch before 1.5 and my controler (domoticz) not support it yet.

**Comment by vil1driver** [comment]
I'm glad you like it.
I just would share my work, and signin github for this.
I hope it will be useful for all like it's for me.
Do you think, my code will be added to the exemple list ?
I can send a breadboard screenhot if needed.

**Comment by vil1driver** [comment]
Thanks a lot

**Pull request merged**
