### PR TITLE
Add sleep handler to optimize low-power sleep

### PR DESCRIPTION
**Pull request by SinishaDjukic**
Sleep handler is invoked right before entering the sleep function, as well a just after the sleep completes. Applications can use this handler to turn off peripherals or put pins into a best possible low power state according to the concrete hardware design.

### CODE REVIEW

**Comment by tekka007** [comment]
The current AVR GCC is v7.3.0 (Arduino Boards v1.8.2) - you can use a weak function definition instead of MY_SLEEP_HANDLER.

**Comment by SinishaDjukic** [comment]
> The current AVR GCC is v7.3.0 (Arduino Boards v1.8.2) - you can use a weak function definition instead of MY_SLEEP_HANDLER.

I followed the same approach as MY_INDICATION_HANDLER, which is somewhat more explicitly visible for the developers, but if weak functions are preferred now I can revise.

**Comment by tekka007** [comment]
I totally agree, please go ahead with your implementation. We may reconsider that in a later update.

**Comment by SinishaDjukic** [comment]
Ready for review & merge

**Pull request merged**
