### PR TITLE
New sensors examples

### PR DESCRIPTION
**Pull request by empierre**
trying the right way. I did not find any setup constructor fot the V_PREFIX stuff so I did a second message sent only at startup, right ?

### CODE REVIEW

**Comment by tbowmo** [comment]
Jenkins, build this please, if you would be so kind

**Comment by henrikekblad** [comment]
Jenkins, build this please.

**Comment by henrikekblad** [comment]
@empierre 
The build server (and Arduino IDE) doesn't seem to like the dual-sketch-in-folder. I suggest you create separate folders for them (with matching sketch name). 

To follow the old "standard" perhaps something like:
AirQualityMHZ14Sensor
DustDSM501Sensor

Guess you have best knowledge regarding which product name mostly used here.

**Comment by empierre** [comment]
ok hek, done tell me if this is good for you !

**Comment by tbowmo** [comment]
Hi Jenkins, build this please

**Comment by empierre** [comment]
Hello, I'm away for 2 weeks, I'll check that afterward for this seems not obvious...

**Comment by fallberg** [comment]
The warning is this:
SoilMoistSensor.ino:137
unused parameter 'sensor' [-Wunused-parameter]

An easy fix would be to remove that parameter since it is not used.

**Comment by empierre** [comment]
@fallberg thanks I hope this is fine this time

**Comment by fallberg** [comment]
Let's gave a go! Jenkins, build this please!

**Comment by henrikekblad** [comment]
Thank you @empierre . Congratulation on having the first pull request going through the new jenkins build server.

**Comment by empierre** [comment]
thanks @henrikekblad I did it the hard way, sorry for that, I'm still noob on the online version of github....

**Pull request merged**
