### PR TITLE
[Enhancement] AutoID for Serial Gateway

### PR DESCRIPTION
**Pull request by funky81**
Following is the patch for Auto ID in Serial Gateway.
Serial Gateway will start from ID 1 till 254 where 255 is the ID for undefined id (temporary) and ID 0 is for the gateway itself

### CODE REVIEW

**Comment by thozza** [comment]
Out of curiosity, I thought the controller is the one assigning Node IDs? With this change, the gateway would always be assigning IDs to nodes.

**Comment by henrikekblad** [comment]
Hi @funky81,

Thanks for the patch but if gateway would start handing out ids we would also have to create control commands for un-assigning id's from the controller side etc. Also, if a user would switch gateway he'd lose the count and gateway would hand out duplicates to new nodes. 

If we would put more "intelligence" in the gateway I would like to se a more complete set of controller<->gateway commands and a gateway that keeps track of sensor net (keep a list of known sensors/actuators). 

Unfortunately the gateway storage on 328p is already over the limit (with message signing enabled) and we would have to step up hardware wise on the gateway to cope with this kind of things.  

The MQTT gateway is today handing out ids but this is not good and will probably change in the future. 

Are you using the gateway with any controller in your setup?

**Comment by funky81** [comment]
I've just know that ID should be given by Gateway. If it work like that,
how is the mechanism?
Currently I'm using Pimatic and as far I check in the source code, it still
doesn't support Auto ID for MySensor.

Thanks

**Comment by funky81** [comment]
I've just realize this, any gateway that support this mechanism? Coz my
gateway, Pimatic, still doesn't support this

Thanks

**Comment by funky81** [comment]
Sorry guys, any response for this? 
If not, then let me have it on my own branch.

Thabks

**Comment by henrikekblad** [comment]
Sorry for a late response.
You'll probably have to have this in your branch until Pimatic supports id-handout.

**Comment by funky81** [comment]
Thanks for your clarification Hek.
May I know, which gateway that already support auto ID? Need to implement
this.

Thanks

**Comment by henrikekblad** [comment]
Most of them. Didn't know that pimatic hadn't implemented it. Maybe you could help them to get it in place?

**Comment by funky81** [comment]
Ok, Thanks Hek. I'll close this PR.

Thanks

**Pull request closed without merging**
