### PR TITLE
Corrected the channel selection

### PR DESCRIPTION
**Pull request by Kolbi**
There are only 125 choosable channel available.

### CODE REVIEW

**Comment by fallberg** [comment]
A lot of commits (17) in this pr. Intentional?

**Comment by Kolbi** [comment]
I'm still trying to get into Github and its techniques. Most commnits are caused because I've been updating my own Development branch. Sadly I don't know how to exclude some commits from a PR.

**Comment by fallberg** [comment]
Generally, you should never make commits on the development branch. That will complicate things for you every time you want to update it or create a pr from it. Typical git work flow when working against a shared repository is to not touch branches shared with the main repository (development and master in this case) and when you want to make a pr, you create a new local branch (typically referred to as a topic branch) that stems from development and push that branch to github. Then you create a pr of that branch. The commits on that branch will be part of the pr. 
If you need to update your branch, you either merge from an updated development branch and push or rebase the branch against a updated development branch and force push.

**Comment by henrikekblad** [comment]
Brought up-to-date in:
https://github.com/mysensors/Arduino/pull/375

**Pull request closed without merging**
