### PR TITLE
Update MyTransportPJON.cpp

### PR DESCRIPTION
**Pull request by gryzli133**
Enabling to define different value of PJON_POLLING_DURATION

### CODE REVIEW

**Comment by Tico06** [comment]
Hi There,
Looks like we have similar issue here
`java.io.IOException: Failed to copy /var/lib/jenkins/jobs/MySensors/jobs/MySensors/branches/PR-1520/workspace/MySensors/hal/transport/PJON/driver/PJONDefines.h:207 to /var/lib/jenkins/jobs/MySensors/jobs/MySensors/branches/PR-1520/builds/6/workspace-files/fe1411a2.tmp
 Caused by: java.nio.file.NoSuchFileException: /var/lib/jenkins/jobs/MySensors/jobs/MySensors/branches/PR-1520/workspace/MySensors/hal/transport/PJON/driver/PJONDefines.h:207`

Please see #1520 

Thx and br

Eric.

**Comment by virtual-maker** [comment]
@Tico06 Hi Eric, 
it looks like PR #1488 has also joined the Toll Gate club. @AdamSlowik has tried some remedial measures, but so far without success. You can read our guesses about the reason in the comments.

Anyone with an idea what to try next?

**Comment by virtual-maker** [comment]
In the .ci folder there is a script which looks like the one which runs on Jenkins for **Toll gate (STM32F1 - Tests)**:
[arduino.groovy#L187](https://github.com/mysensors/MySensors/blob/development/.ci/arduino.groovy#L187)

May be the sub function `parseWarnings()` in this script needs an update?

**Comment by Tico06** [comment]
Hi There,
What about revert .ci back and check if one of the commits in the dir may generated this issue ?
thx and br
Eric.

**Comment by virtual-maker** [comment]
> Hi There, What about revert .ci back and check if one of the commits in the dir may generated this issue ? thx and br Eric.

@Tico06 Hi Eric,
Meanwhile I think the best solution is to fix the issue in the PJON driver file and leave the .ci scripts as they are. I have created an issue #1527 and PR #1528 to fix this.

Now I need to convince @mfalkvidd to merge the PR #1528.

I'm quite sure that the fix is Ok, because the issue is already fixed in the latest PJON repo. And my fix is doing the same.

@gryzli133 It would be very nice and helpful if you could check the fix from PR #1528. Obviously you are using the PJON transport layer in your project. I'm sure your feedback will convince @mfalkvidd even more to merge PR #1528 into development.

BR Immo

**Comment by Tico06** [comment]
Thanks a lot @virtual-maker to support !

How should I proceed ? copy/paste your update in my fork and commit ? Or a nicer way exist ?

thx and br

Eric.

**Comment by virtual-maker** [comment]
> How should I proceed ? copy/paste your update in my fork and commit ? Or a nicer way exist ?

@Tico06 It would be nice, if you could give a comment in PR #1528 about Mikael's and [my comment](https://github.com/mysensors/MySensors/pull/1528#issuecomment-1176568840) and how you see it to proceed.

**Comment by virtual-maker** [comment]
@Tico06 @gryzli133 @AdamSlowik
Ok, Mikael has merged PR #1528 - thank you @mfalkvidd :-)

Now you should rebase your PRs to latest mysensors/development. This will trigger the Toll gate again for your PR and we have to wait for the results.

**Pull request merged**
