### PR TITLE
making MYSENSORS_LIBRARY_VERSION for purposes of being more unique

### PR DESCRIPTION
**Pull request by joshuacox**
not sure if the AltSoftSerial.h file will be affected, but I think I got everything else

```
grep -ir LIBRARY_VERSION *                                                     [13:04:26]
MySensors/core/Version.h:#define MYSENSORS_LIBRARY_VERSION "2.0.0-beta"
MySensors/core/MyGatewayTransport.cpp:                                  gatewayTransportSend(buildGw(_msg, I_VERSION).set(MYSENSORS_LIBRARY_VERSION));
MySensors/core/MySensorsCore.cpp:       debug(PSTR("Starting " MY_NODE_TYPE " (" MY_CAPABILITIES ", " MYSENSORS_LIBRARY_VERSION ")\n"));
MySensors/core/MySensorsCore.cpp:       _sendRoute(build(_msgTmp, _nc.nodeId, GATEWAY_ADDRESS, childSensorId, C_PRESENTATION, sensorType, enableAck).set(childSensorId==NODE_SENSOR_ID?MYSENSORS_LIBRARY_VERSION:description));
MySensors/drivers/AltSoftSerial/keywords.txt:library_version    KEYWORD2
MySensors/drivers/AltSoftSerial/AltSoftSerial.h:        static int library_version() { return 1; } //!< library_version
```

### CODE REVIEW

**Comment by joshuacox** [comment]
Not sure how much detail jenkins wants in the commit message, but this was in reference to #488

**Comment by joshuacox** [comment]
I have force an update to the commit message that should appease Jenkins

**Comment by fallberg** [comment]
Jenkins should have mailed you exactly what it thinks you need to change. From what I can see, your headline is not capitalized.

**Comment by joshuacox** [comment]
now capitalized

**Comment by joshuacox** [comment]
ok, despite a bit of frustration there, I'm pretty impressed.  That's a pretty wicked jenkins setup.

**Comment by fallberg** [comment]
Well, it all serves to provide a better git log for everyone's benefit :) Thanks for appreciating it ;) 
Sorry for the build failures. Not your fault. I recently updated jenkins to use the latest Arduino environment and board support packages, and the esp port is failing. That's not your fault, and there is PR open that fixes it.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Hm, your PR might need a rebase from development branch to pass the builds

**Comment by joshuacox** [comment]
Yeeha, I finally passed the gauntlet!

**Comment by fallberg** [comment]
Jenkins, build examples please. This will likely fail, but hopefully not due to this pr (ide and bsp:s now updated to the latest which some 3rd party libraries does not support and a few examples use these)

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
Jenkins, build examples pleas

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
@joshuacox you need to rebase your PR before re-passing gauntlet...

**Comment by tekka007** [comment]
PR closed due to inactivity

**Comment by joshuacox** [comment]
really you are going to close my pull request on the 4th of july? before I can get back to my home computer where I have the repo that needs to be rebased?

**Comment by Dietmar-Franken** [comment]
7 days are a long time for a open source profect ;-)

**Comment by henrikekblad** [comment]
No problem, just a matter of reopening it. Guess majority of the core team is Europe based ;)

**Comment by fallberg** [comment]
What is so special about 4th July? Birth of a "democracy"? :D

**Comment by joshuacox** [comment]
well beyond that birthday stuff it's a long weekend for me

**Comment by joshuacox** [comment]
there we go, sorry but last thursday (which is not yet 7days ago) I left for Colorado (18 hour road trip).  @fallberg you are very correct to put "democracy" in quotes, the media here plays the droning masses like a fiddle, and when they play the wrong tune they just rig the voting machines to produce whatever they please.  Ignore the TV it will only misinform you.

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Comment by henrikekblad** [comment]
> What is so special about 4th July?

It's like brexit++ :D (oh dear... this is going OT)

**Comment by joshuacox** [comment]
Good deal on the merge! 

@henrikekblad OT but very funny!

**Comment by JohanElmis** [comment]
Hello! 

Just  wanted to  say  hello to you and let you know  that I found something interesting for you, look at it here <http://venue.taylorautorepairs.com/e4dxqay>

Sincerely, johan

**Comment by JohanElmis** [comment]
Hello friend, 

I'm planning an expedition to the Nort Pole,  please take a look at some photos of my  preparations <http://sensation.954realestate.net/e4tklka>


Very truly yours, johan

**Comment by JohanElmis** [comment]
Hey! 


I was  amazed by that shocking article  I've recenly read, please read it and tell me your opinion <http://ltykochetha.sheenabeaston.com/e4gmlppf>

Yours faithfully, johan

**Comment by JohanElmis** [comment]
Dear! 


I met my old friend  yesterday, he is now so famous and talked  by a lot of people. You can find more about him here <http://phuspudupro.njbsg.com/e4uzkwu>

Looking forward, johan

**Comment by JohanElmis** [comment]
Greetings! 


Just take a quick look at my  favourite stuff, you're gonna  love it! More  here  <http://nkyxocapro.zbattle.net/e4dozb>


Speak to you later, johan

**Comment by JohanElmis** [comment]
Hello friend, 
I know you  were  looking  for this, I found this  stuff for you, take a look at <http://faltowunti.duncanclanproductions.com/e4zihro>

Warmest, johan

**Pull request merged**
