### PR TITLE
Add MQTTClientGateway

### PR DESCRIPTION
**Pull request by tomkxy**
MQTTClientGateway acting as a client to the MQTT broker Mosquito.

I agree to the CLA of MySensors.

### CODE REVIEW

**Comment by henrikekblad** [comment]
Jenkins, build this please.

**Comment by henrikekblad** [comment]
Damn, Jenkins.. Build this please.

**Comment by henrikekblad** [comment]
Jenkins, build this please

**Comment by henrikekblad** [comment]
Jenkins, build this please

**Comment by tomkxy** [comment]
Fixed warnings in MQTTClientGateway.

**Comment by tomkxy** [comment]
The latest commit should address the last warning in MQTTClientGateway.

There is one warning in the PubSubClient library which however, I do not want to change because I took it as is.

**Comment by fallberg** [comment]
I think all warnings need to go. Also in 3rd party code. Warnings should never need to exist. The only warnings Jenkins will ignore are the ones located in the standard libraries provided with the Arduino IDE.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by tomkxy** [comment]
Frankly speaking, I do not understand the warning. It says 
"comparison is always false due to limited range of data type [-Wtype-limits]" pointing to the following line

boolean PubSubClient::subscribe(char* topic, uint8_t qos) {
>>>   if (qos < 0 || qos > 1)
     return false;

Although, I understand that qos is defined as unsigned int and thus checking for <0 doesn't seem to make sense, I would still assume that a value of > 1 will evaluate to true.

**Comment by tomkxy** [comment]
Now it should run through without any warnings.

**Comment by henrikekblad** [comment]
Thanks @tomkxy. Let's see.

Jenkins, build this please

**Comment by henrikekblad** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Testing a more lenient Jenkins. Jenkins, build this please.

**Comment by fallberg** [comment]
And even more lenient. Jenkins, build this please.

**Comment by henrikekblad** [comment]
All ok now! 
Thanks @tomkxy

**Pull request merged**
