### PR TITLE
WIP: Cleanup transport code

### PR DESCRIPTION
**Pull request by tekka007**
Fix:
- fix routing table update
- remove pipe/addr dependency for forwarding (driver update separate PR)
- refactoring variables / definitions

Enhancements:
- state machine for transport
- process all msgs in FIFO
- rewrite routing code
- add BC msg callback
- implement controlled BC forwarding
- MY_PARENT_NODE_ID is handled as preferred parent id
- implement fallback function for preferred parent node id (setting MY_PARENT_NODE_IS_STATIC disables fallback)
- OTA firmware update code moved to MyOTAFirmwareUpdate

New functions:
- pinging nodes with hop count if relayed
- node is registering to GW/controller before sending sensor data
- check uplink to GW before replying to I_FIND_PARENT while acting as repeater
- hwFreeMem() to retrieve free memory

New C_INTERNAL msg types:
- I_PING/I_PONG: check connection to specified node and count hops
- I_REGISTER_REQUEST/I_REGISTER_RESPONSE: register node with GW
- I_DEBUG: remote debug (memory 'M', routing table 'R', frequency 'F', voltage 'V')

Tests:
- Signing: ok
- OTA FW update (Sensebdenr): ok
- (Re)-routing: ok

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please (just to see if the pull request build plugin fails for a specific PR or any PR)

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Pull request closed without merging**
