### PR TITLE
Reorganizing library structure, prep for 2.0.0

### PR DESCRIPTION
**Pull request by tbowmo**

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build this please (just testing a cleanup thing on Jenkins)

**Comment by tbowmo** [comment]
Jenkins, build examples build

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Pull request merged**
