### PR TITLE
Update PressureSensor.ino

### PR DESCRIPTION
**Pull request by rico0260**
Last change for me

### CODE REVIEW

**Comment by henrikekblad** [comment]
Please explain what this PR is doing.

Cheers
Henrik

**Comment by rico0260** [comment]
Modification so that table pressureSample is used correctly, and thus to obtain the  good forecast.

Greeting
Eric

**Comment by henrikekblad** [comment]
Have you had time to do long-term testing of your changes?

**Comment by rico0260** [comment]
my sensor is battery operated since April 10, 2015 unfailingly.

**Comment by henrikekblad** [comment]
A new pull request came in that simplified the pressure algoritm even further. I'm going to close this as it's no longer merges.

**Pull request closed without merging**
