### PR TITLE
Added the ability to use URL for mqtt address + fixed mqttclient connect problem

### PR DESCRIPTION
**Pull request by ciknowles**
This is a resubmit of pull request #337 opened 8 hours ago by ciknowles. I've cleaned up my commits and added an appropriate comment as requested.

### CODE REVIEW

**Comment by fallberg** [comment]
I don't really understand the commit log. There seem to be four commits, all with the same headline. Something went wrong somewhere?

**Comment by ciknowles** [comment]
Hi Patrick,

No, I apologise if I've made a mistake again. Nothing went wrong. I'm 
new to Git,  I've used SVN and other version control systems for many 
years but this is the first time using GIT. The software companies that 
I've worked for have never adopted it.

I thought I pushed 4 files to my github account at the same time with 
the same comment as they were all changes required to add in the mqtt 
URL changes.

Let me know if I've messed up again. On a side note, who do I liaise 
with regarding the mqtt in mysensors? I want to commit changes to allow 
QOS and Retained flags to be set.  I have this done but am reluctant to 
push to mysensors unless someone actually thinks it is a good idea. (I 
do but I'm odd....)

Thanks for giving me the time,

Chris

**Comment by fallberg** [comment]
Ok. When creating a commit you add everything you want to include in the commit by "git add". They are then placed in a "staging" area, but nothing is yet committed. Once you issue "git commit" everything in the staging area is then part of that commit. When working with git I would recommend using the command line for all tasks except maybe history browsing. The online git-book and various forum resources provide great help in how to perform various operations. Google is your friend (and mine) :)

**Comment by ciknowles** [comment]
Thanks Patrick,

That is what I did I thought using the command line. I clearly did 
something wrong or added then committed each file separately. I was 
probably trying to make sure I didn't mess up.

I'll keep learning about it - it can't be that difficult!

Thanks,

Chris

**Comment by henrikekblad** [comment]
Look at "squashing commits" here:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by ciknowles** [comment]
Hi Patrick, 

I believe I have fixed the history. I have rebased my fork and committed the resulting 4 changes. If there is still an issue I suggest I close the request and resubmit. Let me know what to do.

Chris

**Comment by fallberg** [comment]
If you go to the top of your PR here, and see on the Commits tab, you will find 19 (!) commits. Somethings is definately not right if you include others commits in your own PR. It does not look like you are in sync with the development branch. It also looks like you are trying to make a PR from your own development branch to MySensors'. And that is generally bad git "practice". You should ALWAYS create a local branch for working on a thing. You create it so that it stems from your development branch, Then you push that branch to github.
Example (assuming mysensors is your remote for the master repo and origin is your fork):
git fetch mysensors (update the mysensors remote database)
git checkout development (make sure you stand on your own development branch)
git merge mysensors/development (should be a fast-forward merge assuming you do not make local changes on the development branch)
git checkout -b topic (create and checkout a new branch called "topic")
(do your stuff, make sure it compiles without warnings and commit):
git add <files>
git commit (enter a nice message)
git push origin HEAD:topic (push your local branch to github and on github create a PR for it)

Now if it appears that your PR is out of sync with the mysensors development branch, you have two options:
1. (the "honest" way)
Repeat the steps above to make your own development branch in sync with the mysensors one
Merge the updates to your topic branch:
git checkout topic
git merge development
git

**Comment by ciknowles** [comment]
Hi Patrick,

A complete and utter disaster then...

I would normally create a branch (or Tag in SVN) but didn't in this case 
as I have no other changes in my repository.

I have 19 other commits as I pressed the button on the Jenkins page that 
says: "This branch is out-of-date with the base branch Merge the latest 
changes from development into this branch". As I submitted the pull 
request a few days ago my repository is out of date.

I believe my problem is that I should have closed the pull request and 
opened a new when the current one became out of date.

I will try again and also branch as you request,

Chris

**Pull request closed without merging**
