### PR TITLE
Fix MY_WITH_LEDS_BLINKING_INVERSE always on/blink off

### PR DESCRIPTION
**Pull request by sundberg84**
Correct MY_WITH_LEDS_BLINKING_INVERSE (Include now means leds are always lit)

### CODE REVIEW

**Comment by fallberg** [comment]
Please be more descriptive in the commit headline. The headline gives no information on what you actually changed.

**Comment by sundberg84** [comment]
Sorry, first request... also didnt sign any agreement but whatever that is i agree to that.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Actually, your commit headline remains unchanged. Please remember to format your commit message a bit better next time :) 
Here is a good guide: http://chris.beams.io/posts/git-commit/

**Comment by sundberg84** [comment]
It changed here in the header on the pull request but not in the build :/
Yes, will read - thank you for the link.

**Comment by fallberg** [comment]
You can't change a commit message without amending the commit and pushing the updated commit. The pr header is the label the merge commit will get but tour own commit will also show in the git history, hence the need for well written commit messages so the history makes sense.

**Comment by fallberg** [comment]
Regarding the actual change, isn't this depending on how the led is connected? What is the default for MySensors? To sink the led or source it? @henrikekblad do you know?

**Comment by sundberg84** [comment]
I have it connected 7,8,9 to Gnd on a Uno with Ethernet Shield if you need that info.

**Comment by fallberg** [comment]
Ok, because the official building instructions have them connected to VCC and the pin sinks the net. So the default behaviour is correct with those instructions.

**Comment by sundberg84** [comment]
Oh, sorry - my misstake then... :( I must have missed that...
Then we can just close/remove this pull I guess.

**Pull request closed without merging**
