### PR TITLE
Backport of bugfix (#259) in repeaters when forwarding signed messages

### PR DESCRIPTION
**Pull request by zaphodus**
This bug still exists in a master branch. I have backported this patch:
"Fixed bug in repeaters when forwarding signed messages #259"

### CODE REVIEW

**Comment by fallberg** [comment]
Please be more descriptive in the commit headline. "Update mysensor.cpp" give absolutely no information on what you have actually changed.

**Comment by zaphodus** [comment]
I am sorry for the incomplete description.  I am using the stable version, where the repeating of signed messages didn't work. So I backported your patch and now it works. It has been tested for two weeks.

**Comment by fallberg** [comment]
You need to amend the commit to change it's title. Your commit remains unchanged: https://github.com/zaphodus/Arduino/commit/ff3f67fa00acfb88555e0385cb5d6153182b7240

By pushing to your branch (patch-1) the PR will automatically update.

**Comment by fallberg** [comment]
Regarding PR:s to master, this is generally not allowed. Only releases get merged to master.
@henrikekblad is the one to discuss with if a new library release is required.

**Comment by fallberg** [comment]
While we are on the topic of fixing issues with signing and repeaters, would you perhaps be so kind to have a look at my PR https://github.com/mysensors/Arduino/pull/305 and see if that makes things go bad on development as well? I don't have the infrastructure to test repeaters unfortunately.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please (sorry for spamming, Jenkins is not doing exactly what I want)

**Comment by fallberg** [comment]
Jenkins, build this please (sorry for spamming, Jenkins is not doing exactly what I want)

**Comment by fallberg** [comment]
I have added your backport to PR #336 which at some point will be part of the next release. Thanks for the backport.

**Comment by zaphodus** [comment]
I have a look at your code (PR #305) and it seems to be good. I am going to switch to the development branch to test it. However, this may take some time as I need to convert my sketches.

**Comment by fallberg** [comment]
Thanks! No rush. I hope we have collected all patches and can release 1.5.2 next week.

**Pull request closed without merging**
