### PR TITLE
Adding Water Quality

### PR DESCRIPTION
**Pull request by mboyer85**
For pool/aquarium water management

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Sorry, jenkins is unstable for the moment. Hope to fix soon

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by henrikekblad** [comment]
Thanks!

**Comment by mboyer85** [comment]
Thanks

**Pull request merged**
