### PR TITLE
implementation of I_DISCOVER

### PR DESCRIPTION
**Pull request by tekka007**
Discovery function for all active (=listening) nodes. Nodes reply with
I_DISCOVER_RESPONSE and the parent node as payload. Useful to retrieve
network topology.

### CODE REVIEW

**Comment by henrikekblad** [comment]
Cool, did you get a chance to test this through a repeater.

**Comment by tekka007** [comment]
Yes, repeater does controlled forwarding

**Comment by henrikekblad** [comment]
Awesome. I'll merge it. 

Maybe 1.6 nodes should send a I_CAPABILITIES message instead of I_CONFIG at startup with the extended information... or both to be backward compatible.

**Comment by tekka007** [comment]
yes, there are still things tbd in terms of included information and encoding (i.e. bit vs. comma-separated values)...

**Pull request merged**
