### PR TITLE
Added support for MQTT over SSL/TLS

### PR DESCRIPTION
**Pull request by rdrgzlng**
With these changes, it is possible to connect a ESP8266 MQTT Gateway to a broker using certificates.

Related #1283

### CODE REVIEW

**Comment by mfalkvidd** [comment]
Nice work!
Could you add documentation on the parameters, similar to existing documentation for MY_MQTT_CLIENT_ID  https://github.com/mysensors/MySensors/blob/b7bed69113982a4d0bf950862df0baf6d9a059f6/MyConfig.h#L1461 ?

This would help people find and understand the new defines. Link to the documentation: https://www.mysensors.org/apidocs/group__GatewaySettingGrpPub.html#gaed25de9bbbe1b73f91ce18105a688217

**Comment by mfalkvidd** [comment]
Is bearssl available automatically in the arduino ide when the esp8266 board definitions are installed?

**Comment by rdrgzlng** [comment]
Thanks mfalkvidd, I will add documentation as you suggested.

BearSSL is available since 2.5.0 release of ESP8266 Arduino board definition and latest MySensors version (2.3.2) requierd the use ESP8266 v2.6.2 board definition.

More info:

https://github.com/esp8266/Arduino/releases/
https://github.com/mysensors/MySensors/releases

**Comment by rdrgzlng** [comment]
Documentation added, as suggested.

Check to see if it is clear and conforms to the guidelines or needs improvement.

**Comment by tekka007** [comment]
@rdrgzlng Please rebase this PR

**Comment by rdrgzlng** [comment]
Done!

**Comment by mfalkvidd** [comment]
Thanks a lot for this contribution. Documentation will be available at https://www.mysensors.org/apidocs-beta/group__GatewaySettingGrpPub.html#gaed25de9bbbe1b73f91ce18105a688217 as soon as the development build is complete.

**Pull request merged**
