### PR TITLE
Add Oregon decoder library

### PR DESCRIPTION
**Pull request by Mickaelh51**
Hi,
I like to add my new Oregon library 1.0.0.

the explanations here: http://forum.mysensors.org/topic/2655/arduino-library-for-oregon-sensors-433mhz

Thanks in advance

### CODE REVIEW

**Comment by henrikekblad** [comment]
Jenkins, add author to whitelist please.

**Comment by fallberg** [comment]
Currently a major PR that affect Jenkins configuration is under review. I suggest we wait with buiding this because it will fail

**Comment by Mickaelh51** [comment]
Hi all,
thanks for the 'whitelist'.

Jenkins has detected two warning in Oregon.h with Arduino IDE it was ok ;). 
Must do I correct them ?

For the last error: "error unknown CPU type" I'm sorry, I don't know it...

**Comment by fallberg** [comment]
Any warning located in code that exist in git should be corrected yes. Warnings belonging to the libraries provided by the IDE need not be corrected (and cannot be corrected).

**Comment by fallberg** [comment]
The error is due to the other PR I mentioned above, and you don't need to worry about that.

**Comment by Mickaelh51** [comment]
OK it's corrected. except that: #1036-MySensors:mysensors_gw_native

**Comment by fallberg** [comment]
You can now fetch the latest development branch and
either
rebase your pr branch and force push it to github to get it rebuilt
or
merge the updates on development to your pr branch and push it to github to get it rebuilt

**Comment by Mickaelh51** [comment]
I will do that tomorrow. Thanks.

**Comment by Mickaelh51** [comment]
Perfect ;)

**Comment by henrikekblad** [comment]
Thanks @Mickaelh51!

**Pull request merged**
